### ISSUE TITLE
Filter some of the authors content

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#106]
Some of the authors need to have filters applied to just PowerShell content.

- @adbertram 
- @zaicnupagadi 
- @nonprofittechy 

Could you filter down to just PowerShell content?

**Comment by nonprofittechy** [comment]
I believe I already have a filter but I might be a little too liberal with what I tag "powershell" currently. I'll take a look and I'm happy to make that a little stricter.

**Comment by zaicnupagadi** [comment]
Same here, will definately try to be more strict! Is putting tag
"PowerShell" on wordpress blog post enough?

2018-04-24 15:12 GMT+02:00 Quinten Steenhuis <notifications@github.com>:

**Comment by adbertram** [comment]
You mean mental health and job burnout aren't PowerShell? 😂

**Comment by kjacobsen** [comment]
@zaicnupagadi If you can use categories within your blog engine (and its RSS) then you could filter based upon that. An Example is in the Readme.

@adbertram It is a hard one, but I would like to try and keep it relevant.

**Comment by kjacobsen** [comment]
Thanks @nonprofittechy for your understanding.
