### ISSUE TITLE
Check all Authors are using HTTPS

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#110]
To make the world a safer place, we should be only linking and checking HTTPS addresses.

On August 1st (2018-08-01) I will be removing any blogs that do not support HTTPS.

I will be posting an announcement up on my blog as well.

**Comment by kjacobsen** [comment]
I have gone through and audited those who do/don't support HTTPS.

The following don't support HTTPS:

- Andreas Bittner @bobruhny 
- Brandon Padgett @gerane 
- David Christian @dchristian3188 
- Josh Duffney @Duffney 
- Mike Robbins @mikefrobbins 
- Mukesh Shende @mukeshshende 
- Nicholas Dille @nicholasdille 
- Sebastian Feldmann @seebus 
- Tommy Maynard @tommymaynard

**Comment by nicholasdille** [comment]
Fix for @nicholasdille by #143

**Comment by dchristian3188** [comment]
Fix for David Christian @dchristian3188  in https://github.com/planetpowershell/planetpowershell/pull/144

**Comment by mikefrobbins** [comment]
Fix for @mikefrobbins in https://github.com/planetpowershell/planetpowershell/pull/146
