### ISSUE TITLE
Determine impact of changes to default filtering

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#112]
Planet Xamarin code now includes default feed filtering to restrict to ~~Xamarin~~ PowerShell content.

This would allow make it easier for new authors, but will need to work out which authors might loose out if their content doesn't have a category of PowerShell or has PowerShell in the title.

My direct suspicion is that this will heavily impact the blogs who are 100% about PowerShell. If this is the case, happy to remove that code and leave it as it currently works.

**Comment by ghost** [comment]
I think my blog is failing to appear on the feed. Do you notice any issues with my author class? Is it something to do with my filter related to this change?

**Comment by yurpcraft** [comment]
I've noticed when I submit a post, my directories get posted instead of the URL as seen here: https://twitter.com/planetpshell/status/1004060947533590528  Could the filtering be doing that, or should I raise a separate issue?

**Comment by kjacobsen** [comment]
Hi @mcbobke and @mcdonaldbm I will split these two issues out from this one as they are not related to the new Planet Xamarin code as it isn't in master (production) yet.
