### ISSUE TITLE
Create Fork, but still it is not reflecting in Planet Powershell

### ISSUE THREAD

**Issue by kunaludapi** [planetpowershell/planetpowershell#132]
Hello,

I have followed the instructions, created a fork and added a KunalUdapi.cs, but I don't see the file in Master, What I am doing wrong. (I have little knowledge of github), below is the fork i created.

https://github.com/kunaludapi/planetpowershell/tree/master/src/Firehose.Web/Authors

**Comment by kjacobsen** [comment]
Hi,

The pull request hasn't been accepted yet. Please reply to the PR for further information.
