### ISSUE TITLE
Tweets from Bryce McDonald's blog appear with broken links.

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#137]
@mcdonaldbm's blog links are well, broken in twitter (need to check facebook too).

See here: https://twitter.com/planetpshell/status/1004060947533590528

Seems the link is broken.

**Comment by kjacobsen** [comment]
Hi @mcdonaldbm 

There is an issue with your RSS feed. The link to the root domain of your blog is missing, combined with the fact your links are references and not fully qualified (ie https://blah.com/blog/post), this results in the issues with how your blog appears.

```xml
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>mcdonaldbm.github.io</title>
<description>
The personal musings of Solutions Engineer and IT Pro Veteran Bryce McDonald
</description>
<link>/</link>
<atom:link href="/feed.xml" rel="self" type="application/rss+xml"/>
<item>
<title>
Adding and Removing Keyboard Languages with PowerShell
</title>

```

**Comment by yurpcraft** [comment]
Ah - I believe I've fixed the issues with my RSS feed.  I'm not sure if it's jekyll that doesn't play nice with xamarin or vice versa, but I've updated my feed.xml to reflect the proper values.

**Comment by kjacobsen** [comment]
Perfect. I will close the issue (but keep an eye on things).
