### ISSUE TITLE
Issues with Bjorn Houben's blog links

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#138]
@bjornhouben's blog links appear to have some unnecessary info.

See: https://twitter.com/planetpshell/status/1005543799140085760

**Comment by kjacobsen** [comment]
Hi @bjornhouben 

I think this is something to do with your atom feed. I see you have an RSS feed. I am going to modify your feed to see if that works.

When are you planning your next post?

**Comment by kjacobsen** [comment]
Re-opening to monitor.

**Comment by bjornhouben** [comment]
I published a new post just now (15-06-2018).

**Comment by bjornhouben** [comment]
@kjacobsen it seems to be working fine now and this can be closed.

**Comment by kjacobsen** [comment]
That is great news. Thanks for letting me know.
