### ISSUE TITLE
Issues with Brandon Olin's blog links

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#140]
Seems @devblackops's blog links are a bit funny. See https://twitter.com/planetpshell/status/1004984555554656257 it goes to https://devblackops.io//https://devblackops.io/how-to-process-file-paths-from-the-pipeline-in-powerShell-functions/

**Comment by kjacobsen** [comment]
Took a quick look at @devblackops's atom feed.

Seems the top level page link has the top level domain name duplicated.

```xml
<description>
Thoughts about DevOps and automation from a Windows guy
</description>
<link>https://devblackops.io/https://devblackops.io/</link>
<atom:link href="https://devblackops.io/https://devblackops.io/feed.xml" rel="self" type="application/rss+xml"/>
<pubDate>Sun, 10 Jun 2018 07:14:49 +0000</pubDate>
<lastBuildDate>Sun, 10 Jun 2018 07:14:49 +0000</lastBuildDate>
<generator>Jekyll v3.7.3</generator>
```

@devblackops can you take a look and fix?

**Comment by devblackops** [comment]
@kjacobsen Should be fixed now. I had some errors in Jekyll.

**Comment by kjacobsen** [comment]
Thanks. I will close the issue but keep an eye on everything and let you know if there are any more problems.

**Comment by kjacobsen** [comment]
I think there are still some issues. I will check the feed to confirm.

**Comment by devblackops** [comment]
Ok. Let me know if you find something.

**Comment by kjacobsen** [comment]
Hmm, just took another look and it is fine. I must have imagined it.
