### ISSUE TITLE
Filtering does not work

### ISSUE THREAD

**Issue by SConstantinou** [planetpowershell/planetpowershell#162]
Hello,

I am using category filtering for the word "PowerShell" and it seems that it pulls everything. The category I am using now is "Modules Cmdlets" and it should not pull all these posts.

Thanks
Stephanos

**Comment by kjacobsen** [comment]
F.Y.I I think I know the issue, I have tweaked your filter so it should now work, I will now need to go back and check everyone's blogs!

Thanks for picking this one up.

**Comment by kjacobsen** [comment]
Still seems to be an issue.

**Comment by SConstantinou** [comment]
Latest filter you have applied still does not work

**Comment by kjacobsen** [comment]
Hey @SConstantinou have you posted anything recently? Just want to do some more testing.

**Comment by SConstantinou** [comment]
Hi Kieran,

I haven't posted anything recently. I will do in a few days not powershell
related. It should be filtered out.

Thank you
Stephanos Constantinou
www.sconstantinou.com

**Comment by kjacobsen** [comment]
Hey, just checking to see if the filtering worked?

**Comment by kjacobsen** [comment]
Ok, I poked at it, and this time, i feel pretty confident I have fixed the filtering issues.
