### ISSUE TITLE
Twitter links do not work propertly

### ISSUE THREAD

**Issue by doctordns** [planetpowershell/planetpowershell#247]
I have posted a tweet that points to a blog article. If I examine the sweet feed, I see:

![2020-01-09_16-12-58](https://user-images.githubusercontent.com/3630329/72084635-bdc1db80-32fb-11ea-8af8-80deb3bf6312.png)

It shows as the first entry, my blog posts. Not sure whythere are so many links...

But if I click on the first one, I see this:

![2020-01-09_16-13-35](https://user-images.githubusercontent.com/3630329/72084687-daf6aa00-32fb-11ea-9120-28d43216aaff.png)

If I delete the characters ".@href" from the end of the URL, I see the page correctly:
![2020-01-09_16-14-03](https://user-images.githubusercontent.com/3630329/72084738-f497f180-32fb-11ea-9360-9104639f3fb1.png)

**Comment by kjacobsen** [comment]
This is often caused by ATOM feed and not RSS 2.0 feeds. I have updated PR #246 to use the RSS feed, hopefully that resolves the issue.

**Comment by doctordns** [comment]
Seems fixed for now!

Thanks!
