### ISSUE TITLE
Some Pictures are not showing

### ISSUE THREAD

**Issue by doctordns** [planetpowershell/planetpowershell#249]
In the Preview Feed - blog posts from my blog do not have my picture associated.

Is there something I need to set in the Author.cs file?

**Comment by kjacobsen** [comment]
Your image is pulled from Gravatar. If you don't have an account (or image) there, then it grabs the default image.

**Comment by doctordns** [comment]
I thought I had done that. Fixed (on Gravitar)

:-)
