### ISSUE TITLE
Prod Deployment Failing

### ISSUE THREAD

**Issue by kevincallanan** [planetpowershell/planetpowershell#263]
@kjacobsen , - it looks like the deployment step is failing to deploy in production due to an issue with the Azure Vault: 

2020-06-27T06:48:30.9347067Z ##[error]
cloudflareapikey: "Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired."
cloudflareapiuser: "Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired."

**Comment by kjacobsen** [comment]
Hey @kevincallanan,

Seems the principle for Azure DevOps had died. Recreated it and all is good.

Thanks for letting me know.
