### ISSUE TITLE
Broken Feed - Evgeny Fedorov

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#285]
Hey @evgenyfedorov2,

Your websites certificate isn't valid, and Planet PowerShell cannot connect to your RSS feed.

I have temporarily removed you from our authors.

Could you please take a look?

**Comment by evgenyfedorov2** [comment]
Hi @kjacobsen 

Please remove me permanently. I am not planning to write to the blog in the upcoming future
