### ISSUE TITLE
Are all properties mandatory?

### ISSUE THREAD

**Issue by beatcracker** [planetpowershell/planetpowershell#31]
Just curious, if I could add [my blog](https://beatcracker.wordpress.com/) without providing `LastName` and `Geoposition`? If yes, should I just add empty strings or remove properties altogether?

Thanks!

**Comment by kjacobsen** [comment]
You will need to include the properties, otherwise it will not build.

Is there any reason you don't want to use your `LastName` or provide a rough `GeoPosition`?

**Comment by beatcracker** [comment]
No other reason, besides my innate paranoia ¬_¬ . I'd be happy to use my GitHub handle as a `FirstName` and very rough `GeoPosition` if this is OK with you.

**Comment by kjacobsen** [comment]
I would like to say yes, but I really want to encourage this to be an open community, where we share out names. Sorry if this means you cannot be a part of Planet PowerShell.

**Comment by beatcracker** [comment]
No problem, keep up the good work.
