### ISSUE TITLE
Add #PowerShell hash tag and via #AuthorTwitterHandle

### ISSUE THREAD

**Issue by dfinke** [planetpowershell/planetpowershell#42]
Wondering if you're planning to add the #PowerShell hash tag and via #AuthorTwitterHandle when the blog title is tweeted?

**Comment by kjacobsen** [comment]
I think I can add the #PowerShell hash tag, but I will need to see if I can do the Author's twitter handle. It is all running via Zapier.

**Comment by kjacobsen** [comment]
Done via Zapier.
