### ISSUE TITLE
Users with // in their links

### ISSUE THREAD

**Issue by kjacobsen** [planetpowershell/planetpowershell#53]
Some users blogs feeds have additional / in link URLs. EG: http://duffney.io//IntroToRegex-LabSetup

Not sure if it is breaking anything, yet.

Impacted Users:
* Josh Duffney
* Doug Finke

**Comment by dfinke** [comment]
Any thoughts on what I can change on my end? Seems like this only started with my last post. Previous one worked.

**Comment by kjacobsen** [comment]
Are there any settings around the generation of the links and permalinks?

**Comment by kjacobsen** [comment]
This issue seems to have been resolved, not sure how, but the feeds look good.

Closing.
