### ISSUE TITLE
Author name missing

### ISSUE THREAD

**Issue by Graham-Beer** [planetpowershell/planetpowershell#86]
Hi, 

When looking at the feed my name does not appear under the author. How can I resolve this ?

Thanks,

Graham Beer

**Comment by kjacobsen** [comment]
Hi Graham,

Took a quick look. From what I am seeing the code looks for either ```<author>The Author</author>``` or ```<dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Mike F Robbins</dc:creator>``` tags in the RSS feed.

**Comment by evgenyfedorov2** [comment]
Hi all,

My RSS feed contains this:

`<dc:creator><![CDATA[ Evgeny Fedorov ]]></dc:creator>`

Can this template be added to the code?

**Comment by kjacobsen** [comment]
Hi @evgenyfedorov2 

Happy to accept a Pull Request from you to include support for that.

**Comment by kjacobsen** [comment]
@evgenyfedorov2 Just took a look, quite a few have the same structure as you do. Is the author not showing up for you either?

**Comment by evgenyfedorov2** [comment]
Hi @kjacobsen 

Just to double-check - I go [here](https://www.planetpowershell.com/feed) and just do Ctrl-F for my name and cannot find anything. Is this the correct way to confirm my name does not appear?

And yes, I will take a look in the code later on to check if I am able to come up with the PR

**Comment by Graham-Beer** [comment]
Resolved
