### ISSUE TITLE
FirstAwarded in explicit interface declaration is not a member of interface	Firehose.Web

### ISSUE THREAD

**Issue by dfinke** [planetpowershell/planetpowershell#9]
Trying to add this `DateTime IAmAMicrosoftMVP.FirstAwarded => new DateTime(2008, 4, 1);`

Get this error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0539	'DougFinke.FirstAwarded' in explicit interface declaration is not a member of interface	Firehose.Web	

C:\Users\Douglas\Documents\GitHub\planetpowershell\src\Firehose.Web\Authors\DougFinke.cs	36	Active
```

**Comment by kjacobsen** [comment]
Thanks @dfinke, I will check with the code and the Xamarin version and see what is happening.

**Comment by kjacobsen** [comment]
I have uncommented your FirstAwarded date.

**Comment by kjacobsen** [comment]
So I discussed this with PlanetXamarin, and they are no longer in use. I have removed the IAmAMicrosoftMVP.FirstAwarded logic.
